### ISSUE TITLE
Bump to v1.0.1 on Packagist

### ISSUE THREAD

**Issue by Stijn-Flipper** [PhileCMS/ComposerPluginInstaller#2]
The current latest version [on packagist](https://packagist.org/packages/phile-cms/plugin-installer-plugin) uses v1.0.0, which doesn't include the fix on PR #1 . Can you update the packagist so that it uses the latest version (v1.0.1)?

This is related to issue https://github.com/Stijn-Flipper/philePaginator/issues/2 . I don't want to force the user to use the `dev-master` version of the plugin installer anyway (since my vendor name has a dash in it).

**Comment by NeoBlack** [comment]
thx for the hint, I have releases 1.0.2, this was important, because 1.0.1 contains wrong version number in composer.json. technical 1.0.1 and 1.0.2 are identical.

**Comment by Stijn-Flipper** [comment]
It's better if you leave out the version field from `composer.json` if you're publishing it to packagist.org only. It will then automatically recognize the tags versions. See also:

    $ composer validate
    ./composer.json is valid, but with a few warnings
    See http://getcomposer.org/doc/04-schema.md for details on the schema
    The version field is present, it is recommended to leave it out if the package is published on Packagist.

**Comment by NeoBlack** [comment]
> Note: Packagist uses VCS repositories, so the statement above is very much true for Packagist as well. Specifying the version yourself will most likely end up creating problems at some point due to human error.

good hint ;) will remove the version property.
